import matplotlib.pyplot as plt
import numpy as np


fieldEnergy4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/fieldEnergy.txt')
time_fieldEnergy4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/fieldEnergy_time.txt')
Iontemp4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/ion_intM2Thermal.txt')
time_Iontemp4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/ion_intM2Thermal_time.txt')
Elctemp4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/elc_intM2Thermal.txt')
time_Elctemp4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/elc_intM2Thermal_time.txt')
current4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/elc_intM1i.txt')*2
time_current4 = np.loadtxt('./Diagnostics/local/Cori/mass25/rescheck/4/saved_data/elc_intM1i_time.txt')
dJdt4 = np.zeros(np.size(current4)-1)
nu_eff4 = np.zeros(np.size(current4)-1)
for i in range(np.size(current4)-1):
    dJdt4[i] = (current4[i+1] - current4[i]) / (time_current4[i+1] - time_current4[i])
for i in range(np.size(current4)-1):
    nu_eff4[i] = (0.00005 - dJdt4[i]) / current4[i]

fig      = plt.figure(figsize=(6.5,5.5))
ax      = fig.add_axes([0.16, 0.16, 0.8, 0.75])
#ax.set_title("perturbed electric field energy",fontsize=16)
ax.plot(time_fieldEnergy4,fieldEnergy4,label='#4',linewidth=5)
ax.set_xlabel(r'$t \quad [\omega_{pe}^-1]$',fontsize=16)
ax.set_ylabel(r'$\int |\delta E_z|^2 + |\delta E_y|^2  dydz$',fontsize=16)
ax.set_yscale('log')
ax.set_xlim(0,2000)
ax.tick_params(labelsize = 14)
#ax.legend(fontsize=14)
plt.savefig('./Diagnostics/local/Cori/figure_temp/field_energy.jpg')
plt.clf()

fig      = plt.figure(figsize=(6.5,5.5))
ax      = fig.add_axes([0.16, 0.16, 0.75, 0.75])
#ax.set_title("perturbed electric field energy",fontsize=16)
ax.plot(time_Iontemp4,Iontemp4,label='#4',linewidth=5)
ax.set_xlabel(r'$t \quad [\omega_{pe}^-1]$',fontsize=16)
ax.set_ylabel(r'$T_i/T_{i0}$',fontsize=16)
ax.set_xlim(0,2000)
ax.tick_params(labelsize = 14)
plt.savefig('./Diagnostics/local/Cori/figure_temp/ion_temp.jpg')
plt.clf()

fig      = plt.figure(figsize=(6.5,5.5))
ax      = fig.add_axes([0.16, 0.16, 0.75, 0.75])
#ax.set_title("perturbed electric field energy",fontsize=16)
ax.plot(time_Elctemp4,Elctemp4/Elctemp4[0],label='#4',linewidth=5)
ax.set_xlabel(r'$t \quad [\omega_{pe}^-1]$',fontsize=16)
ax.set_ylabel(r'$T_e/T_{e0}$',fontsize=16)
ax.set_xlim(0,2000)
ax.tick_params(labelsize = 14)
plt.savefig('./Diagnostics/local/Cori/figure_temp/elc_temp.jpg')
plt.clf()

fig      = plt.figure(figsize=(6.5,5.5))
ax      = fig.add_axes([0.16, 0.16, 0.75, 0.75])
#ax.set_title("perturbed electric field energy",fontsize=16)
ax.plot(time_Iontemp4,Iontemp4/Iontemp4[0],label='#4',linewidth=5)
ax.set_xlabel(r'$t \quad [\omega_{pe}^-1]$',fontsize=16)
ax.set_ylabel(r'$T_i/T_{i0}$',fontsize=16)
ax.set_xlim(0,2000)
ax.tick_params(labelsize = 16)
plt.savefig('./Diagnostics/local/Cori/figure_temp/ion_temp.jpg')
plt.clf()

fig      = plt.figure(figsize=(6.5,5.5))
ax      = fig.add_axes([0.16, 0.16, 0.75, 0.75])
#ax.set_title("perturbed electric field energy",fontsize=16)
ax.plot(time_current4,current4,label='#4',linewidth=5)
ax.set_xlabel(r'$t \quad [\omega_{pe}^-1]$',fontsize=16)
ax.set_ylabel(r'$<J_z> [en_0 v_{te}]$',fontsize=16)
ax.set_xlim(0,2000)
ax.tick_params(labelsize = 16)
plt.show()
# plt.savefig('./Diagnostics/local/Cori/figure_temp/current.jpg')
# plt.clf()